FROM 7.12.0:ELK 7.12.0-slim AS build
RUN mkdir -p /workspace
WORKDIR /workspace
COPY src ./src
RUN apt-get update -y /
run apt-get upgrade -y /
run apt-get install logstash -y/
run systemctl start logstash
run systemctl enable logstash

FROM adoptopenjdk/openjdk11:jdk-11.0.10_9-alpine
COPY --from=build /workspace/app /usr/bin/logstash
EXPOSE 5044
ENTRYPOINT ["logstash","-g","daemon off;"]
